### ISSUE TITLE
tag repo

### ISSUE THREAD

**Issue by kevinpapst** [neontribe/KimaiCvsImportBundle#1]
Hi & thanks for sharing!
Just a question regarding the repo: would you mind to manage the repos topics and add the labels `kimai`, `kimai-timetracking`, `kimai-bundle`, `kimai-plugin`, `kimai2`?
That makes it easier to find it on Github.
ping @tobybatch

**Comment by tobybatch** [comment]
done

**Comment by kevinpapst** [comment]
that was crazy fast 🚀
